export interface Game {
  id: string;
  name: string;
  description: string;
  category: 'Memory' | 'Focus' | 'Speed' | 'Logic';
  cognitiveArea: string;
  difficulty: 'Easy' | 'Medium' | 'Hard';
  duration: string;
  icon: string;
  iconSet: string;
  premium: boolean;
  color: string;
}

const GAMES: Game[] = [
  {
    id: 'ghost-grid',
    name: 'Neuro Grid',
    description: 'Study the city. Watch it vanish. Rebuild it from memory.',
    category: 'Memory',
    cognitiveArea: 'Spatial Working Memory',
    difficulty: 'Medium',
    duration: '3 min',
    icon: 'map',
    iconSet: 'Ionicons',
    premium: false,
    color: '#22D3EE',
  },
  {
    id: 'mind-map',
    name: 'Mind Map',
    description: 'Watch a pattern of tiles illuminate, then tap them back from memory. Train your spatial working memory.',
    category: 'Memory',
    cognitiveArea: 'Spatial Working Memory',
    difficulty: 'Medium',
    duration: '90s',
    icon: 'grid',
    iconSet: 'Ionicons',
    premium: false,
    color: '#818CF8',
  },
  {
    id: 'signal-spotter',
    name: 'Signal Spotter',
    description: 'Identify and tap only the designated target among fast-moving distractors. Train your selective attention.',
    category: 'Focus',
    cognitiveArea: 'Selective Attention',
    difficulty: 'Medium',
    duration: '60s',
    icon: 'radio',
    iconSet: 'Ionicons',
    premium: false,
    color: '#A78BFA',
  },
  {
    id: 'colour-match',
    name: 'Colour Match',
    description: 'Study a colour for 5 seconds, then recreate it using hue, saturation, and lightness sliders. Train your visual working memory.',
    category: 'Memory',
    cognitiveArea: 'Visual Working Memory',
    difficulty: 'Medium',
    duration: '3 min',
    icon: 'color-palette',
    iconSet: 'Ionicons',
    premium: false,
    color: '#F472B6',
  },
  {
    id: 'story-recall',
    name: 'Story Recall',
    description: 'Read a short story once, then answer recall and inference questions. Test your context awareness.',
    category: 'Memory',
    cognitiveArea: 'Context Awareness',
    difficulty: 'Easy',
    duration: '2 min',
    icon: 'book',
    iconSet: 'Ionicons',
    premium: false,
    color: '#6BCDEF',
  },
  {
    id: 'code-cracker',
    name: 'Code Cracker',
    description: 'Crack a hidden 4-digit code using logical deduction and feedback from each guess.',
    category: 'Logic',
    cognitiveArea: 'Deductive Logic',
    difficulty: 'Medium',
    duration: '3 min',
    icon: 'lock-closed',
    iconSet: 'Ionicons',
    premium: false,
    color: '#F59E0B',
  },
  {
    id: 'travel-bag',
    name: 'Travel Bag',
    description: 'Memorize a sequence of items, then reproduce them in the exact order they appeared.',
    category: 'Memory',
    cognitiveArea: 'Memory Sequencing',
    difficulty: 'Easy',
    duration: '90s',
    icon: 'bag',
    iconSet: 'Ionicons',
    premium: false,
    color: '#6EE7B7',
  },
  {
    id: 'detectives-notebook',
    name: "Detective's Notebook",
    description: 'Study a scene carefully, then answer specific questions about object positions and details.',
    category: 'Logic',
    cognitiveArea: 'Observation',
    difficulty: 'Hard',
    duration: '2 min',
    icon: 'search',
    iconSet: 'Ionicons',
    premium: true,
    color: '#F9A8D4',
  },
  {
    id: 'sorting-flow',
    name: 'Sorting Flow',
    description: 'Sort items by a rule that changes mid-session without warning. Test your cognitive flexibility.',
    category: 'Logic',
    cognitiveArea: 'Cognitive Flexibility',
    difficulty: 'Hard',
    duration: '90s',
    icon: 'layers',
    iconSet: 'Ionicons',
    premium: true,
    color: '#969EFF',
  },
  {
    id: 'time-lock',
    name: 'Time Lock',
    description: 'No countdown shown. Tap exactly when you believe the target time has elapsed. Trust your inner clock.',
    category: 'Focus',
    cognitiveArea: 'Internal Timing',
    difficulty: 'Medium',
    duration: '3 min',
    icon: 'timer',
    iconSet: 'MaterialIcons',
    premium: false,
    color: '#D6AEFF',
  },
  {
    id: 'multitask-challenge',
    name: 'Multi-Task Challenge',
    description: 'Track a timer while answering an interrupting question. Manage two tasks simultaneously.',
    category: 'Speed',
    cognitiveArea: 'Task Switching',
    difficulty: 'Hard',
    duration: '2 min',
    icon: 'flash',
    iconSet: 'Ionicons',
    premium: true,
    color: '#FB923C',
  },
  {
    id: 'endurance-run',
    name: 'Endurance Run',
    description: 'Balance on a narrowing path for as long as possible. Build persistence through deliberate difficulty.',
    category: 'Focus',
    cognitiveArea: 'Persistence',
    difficulty: 'Hard',
    duration: 'Until fail',
    icon: 'footsteps',
    iconSet: 'Ionicons',
    premium: false,
    color: '#34D399',
  },
  {
    id: 'focus-anchor',
    name: 'Focus Anchor',
    description: 'React only when the central object changes while ignoring all peripheral chaos and distractions.',
    category: 'Focus',
    cognitiveArea: 'Sustained Attention',
    difficulty: 'Medium',
    duration: '60s',
    icon: 'locate',
    iconSet: 'Ionicons',
    premium: false,
    color: '#7DD3FC',
  },
  {
    id: 'beat-recall',
    name: 'Beat Recall',
    description: 'Listen to a rhythmic sequence of tones, then reconstruct the exact pattern using shuffled buttons.',
    category: 'Memory',
    cognitiveArea: 'Auditory Working Memory',
    difficulty: 'Medium',
    duration: '90s',
    icon: 'musical-notes',
    iconSet: 'Ionicons',
    premium: true,
    color: '#E879F9',
  },
  {
    id: 'drift-control',
    name: 'Drift Control',
    description: 'Keep a moving indicator precisely within a narrow zone. Smooth micro-control is rewarded.',
    category: 'Speed',
    cognitiveArea: 'Micro-Control & Impulse Regulation',
    difficulty: 'Hard',
    duration: '60s',
    icon: 'navigate-circle',
    iconSet: 'Ionicons',
    premium: true,
    color: '#94A3B8',
  },
  {
    id: 'signal-override',
    name: 'Signal Override',
    description: "Tap every colour except the signal. Override your impulse. Don't touch the wrong colour.",
    category: 'Focus',
    cognitiveArea: 'Inhibitory Control',
    difficulty: 'Medium',
    duration: '30 sec',
    icon: 'radio-button-on',
    iconSet: 'Ionicons',
    premium: false,
    color: '#F97316',
  },
  {
    id: 'word-morph',
    name: 'WordMorph',
    description: 'Transform one word into another by changing a single letter at a time. Every step must be a real word.',
    category: 'Logic',
    cognitiveArea: 'Verbal Flexibility',
    difficulty: 'Medium',
    duration: '3 min',
    icon: 'text',
    iconSet: 'Ionicons',
    premium: false,
    color: '#A3E635',
  },
];

export default GAMES;
